# Generated by Django 3.2.6 on 2021-08-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='Phone',
            new_name='phone',
        ),
    ]
