# Generated by Django 3.2.6 on 2021-08-09 14:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Blog Authors', verbose_name='Author Image')),
                ('first_name', models.CharField(max_length=255, verbose_name='Author FirstName')),
                ('first_name_en', models.CharField(max_length=255, null=True, verbose_name='Author FirstName')),
                ('first_name_uz', models.CharField(max_length=255, null=True, verbose_name='Author FirstName')),
                ('first_name_ru', models.CharField(max_length=255, null=True, verbose_name='Author FirstName')),
                ('last_name', models.CharField(max_length=255, verbose_name='Author LastName')),
                ('last_name_en', models.CharField(max_length=255, null=True, verbose_name='Author LastName')),
                ('last_name_uz', models.CharField(max_length=255, null=True, verbose_name='Author LastName')),
                ('last_name_ru', models.CharField(max_length=255, null=True, verbose_name='Author LastName')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Author Created')),
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
            },
        ),
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Category Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Category Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Category Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Category Created')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogTagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tag Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tag Created')),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog images', verbose_name='Blog Image')),
                ('banner', models.ImageField(upload_to='blog banners', verbose_name='Blog Banner')),
                ('title', models.CharField(max_length=255, verbose_name='Blog Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Blog Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Blog Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Blog Title')),
                ('little_about', models.TextField(verbose_name='Little About Blog')),
                ('little_about_en', models.TextField(null=True, verbose_name='Little About Blog')),
                ('little_about_uz', models.TextField(null=True, verbose_name='Little About Blog')),
                ('little_about_ru', models.TextField(null=True, verbose_name='Little About Blog')),
                ('full_about', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Full About Blog')),
                ('full_about_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Full About Blog')),
                ('full_about_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Full About Blog')),
                ('full_about_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Full About Blog')),
                ('blog_views', models.IntegerField(default=0, verbose_name='Blog Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Blog Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Blog Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.blogauthormodel', verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.blogcategorymodel', verbose_name='Category')),
                ('tags', models.ManyToManyField(related_name='blogs', to='blog.BlogTagsModel', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
