# Generated by Django 3.2.6 on 2021-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About Author'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author Job'),
        ),
    ]
