# Generated by Django 3.2.6 on 2021-08-10 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogmodel', verbose_name='Blog'),
            preserve_default=False,
        ),
    ]
