# Generated by Django 3.2.6 on 2021-08-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
            ],
            options={
                'verbose_name': 'Newsletter Member',
                'verbose_name_plural': 'Newsletter Members',
            },
        ),
    ]
