# Generated by Django 3.2.6 on 2021-08-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='about_en',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='about_uz',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Position'),
        ),
    ]
