# Generated by Django 3.2.6 on 2021-08-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_wishlist'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='products.ProductModel', verbose_name='User'),
        ),
    ]
