# Generated by Django 3.2.6 on 2021-08-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tag Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tag Created')),
            ],
            options={
                'verbose_name': 'Product Brand',
                'verbose_name_plural': 'Product Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Category Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Category Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Category Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Category Created')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tag Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tag Created')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors ',
            },
        ),
        migrations.CreateModel(
            name='ProductTagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tag Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Tag Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tag Created')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='products', verbose_name='Product Image 1')),
                ('image_2', models.ImageField(upload_to='products', verbose_name='Product Image 2')),
                ('title', models.CharField(max_length=50, verbose_name='Product Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Product Title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='Product Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Product Title')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('little_about', models.TextField(verbose_name='Little About Product')),
                ('little_about_en', models.TextField(null=True, verbose_name='Little About Product')),
                ('little_about_uz', models.TextField(null=True, verbose_name='Little About Product')),
                ('little_about_ru', models.TextField(null=True, verbose_name='Little About Product')),
                ('full_about', models.TextField(verbose_name='Full About Product')),
                ('full_about_en', models.TextField(null=True, verbose_name='Full About Product')),
                ('full_about_uz', models.TextField(null=True, verbose_name='Full About Product')),
                ('full_about_ru', models.TextField(null=True, verbose_name='Full About Product')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In Stock')),
                ('product_views', models.IntegerField(default=0, verbose_name='Product Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productbrandmodel', verbose_name='Brand')),
                ('categories', models.ManyToManyField(related_name='products', to='products.ProductCategoryModel', verbose_name='Categories')),
                ('colors', models.ManyToManyField(related_name='products', to='products.ProductColorModel', verbose_name='Colors')),
                ('tags', models.ManyToManyField(related_name='products', to='products.ProductTagsModel', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
